"""
BTC Bollinger Band + MACD + RSI Signal Chart
=============================================
Visualises buy/sell signals generated by combining:
  - Bollinger Bands (price touches lower band → buy candidate)
  - RSI (< 30 oversold / > 70 overbought)
  - MACD crossover confirmation

Data source: Refinitiv Eikon (BTC=)
"""

import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime

import eikon as ek

# ── Config ────────────────────────────────────────────────────────────────────
EIKON_APP_KEY = os.environ.get("EIKON_APP_KEY", "YOUR_KEY_HERE")
START         = "2024-06-01"
END           = datetime.today().strftime("%Y-%m-%d")

# ── Data ──────────────────────────────────────────────────────────────────────
ek.set_app_key(EIKON_APP_KEY)
btc = ek.get_timeseries("BTC=", start_date=START, end_date=END)
btc.dropna(inplace=True)

# Moving averages
btc["MA50"]  = btc["CLOSE"].rolling(50).mean()
btc["MA200"] = btc["CLOSE"].rolling(200).mean()

# Bollinger Bands (20-day, 2 std dev)
btc["BB_Mid"] = btc["CLOSE"].rolling(20).mean()
btc["BB_Std"] = btc["CLOSE"].rolling(20).std()
btc["BB_High"] = btc["BB_Mid"] + 2 * btc["BB_Std"]
btc["BB_Low"]  = btc["BB_Mid"] - 2 * btc["BB_Std"]

# RSI (14-day)
delta      = btc["CLOSE"].diff()
gain       = delta.where(delta > 0, 0).rolling(14).mean()
loss_r     = (-delta.where(delta < 0, 0)).rolling(14).mean()
btc["RSI"] = 100 - (100 / (1 + gain / loss_r))

# MACD
ema12          = btc["CLOSE"].ewm(span=12, adjust=False).mean()
ema26          = btc["CLOSE"].ewm(span=26, adjust=False).mean()
btc["MACD"]    = ema12 - ema26
btc["MACD_Sig"]  = btc["MACD"].ewm(span=9, adjust=False).mean()
btc["MACD_Hist"] = btc["MACD"] - btc["MACD_Sig"]

btc.dropna(inplace=True)

# ── Signals ───────────────────────────────────────────────────────────────────
btc["Buy"]  = (btc["CLOSE"] < btc["BB_Low"]) | (
    (btc["RSI"] < 30) & (btc["MACD"] > btc["MACD_Sig"])
)
btc["Sell"] = (btc["RSI"] > 70) & (btc["MACD"] < btc["MACD_Sig"])

# ── Chart ─────────────────────────────────────────────────────────────────────
fig, (ax1, ax2, ax3, ax4) = plt.subplots(4, 1, figsize=(14, 14), sharex=True)

# Price + Bollinger Bands + MAs + signals
ax1.plot(btc.index, btc["CLOSE"],   label="BTC Price", color="black", linewidth=1)
ax1.plot(btc.index, btc["BB_Mid"],  label="BB Mid",    linestyle="--", color="gray")
ax1.plot(btc.index, btc["BB_High"], label="BB High",   linestyle="--", color="green")
ax1.plot(btc.index, btc["BB_Low"],  label="BB Low",    linestyle="--", color="red")
ax1.plot(btc.index, btc["MA50"],    label="MA50",  color="blue",   linewidth=1)
ax1.plot(btc.index, btc["MA200"],   label="MA200", color="orange", linewidth=1)
ax1.fill_between(btc.index, btc["BB_Low"], btc["BB_High"], alpha=0.05, color="blue")
ax1.scatter(btc.index[btc["Buy"]],  btc["CLOSE"][btc["Buy"]],
            marker="^", color="green", s=80, label="Buy Signal",  zorder=5)
ax1.scatter(btc.index[btc["Sell"]], btc["CLOSE"][btc["Sell"]],
            marker="v", color="red",   s=80, label="Sell Signal", zorder=5)
ax1.set_title("BTC Price — Bollinger Bands, MA50/200 & Signals")
ax1.legend(loc="upper left", fontsize=8)
ax1.grid(True, alpha=0.3)

# MACD line + signal
ax2.plot(btc.index, btc["MACD"],     label="MACD",   color="blue")
ax2.plot(btc.index, btc["MACD_Sig"], label="Signal", color="orange")
ax2.axhline(0, color="gray", linestyle="--", linewidth=0.8)
ax2.set_title("MACD & Signal Line")
ax2.legend(loc="upper left", fontsize=8)
ax2.grid(True, alpha=0.3)

# MACD histogram
colours = ["green" if v >= 0 else "red" for v in btc["MACD_Hist"]]
ax3.bar(btc.index, btc["MACD_Hist"], color=colours, label="MACD Histogram", alpha=0.7)
ax3.axhline(0, color="black", linestyle="--", linewidth=0.8)
ax3.set_title("MACD Histogram")
ax3.legend(loc="upper left", fontsize=8)
ax3.grid(True, alpha=0.3)

# RSI
ax4.plot(btc.index, btc["RSI"], label="RSI", color="purple")
ax4.axhline(70, color="red",   linestyle="--", alpha=0.7, label="Overbought (70)")
ax4.axhline(30, color="green", linestyle="--", alpha=0.7, label="Oversold (30)")
ax4.fill_between(btc.index, 30, btc["RSI"], where=btc["RSI"] < 30, color="green", alpha=0.15)
ax4.fill_between(btc.index, 70, btc["RSI"], where=btc["RSI"] > 70, color="red",   alpha=0.15)
ax4.set_ylim(0, 100)
ax4.set_title("RSI (14)")
ax4.set_xlabel("Date")
ax4.legend(loc="upper left", fontsize=8)
ax4.grid(True, alpha=0.3)

plt.suptitle(f"BTC Technical Indicators  ({START} → {END})", fontsize=13, y=1.01)
plt.tight_layout()
plt.show()
