"""
BTC Technical Indicator Dashboard
===================================
Loads hourly BTC-GBP data from the local CSV and computes:
  MA50, MA200, Bollinger Bands, RSI, ATR, OBV

Then plots a 5-panel dashboard for the most recent N days.

Data source: btc_gbp_hourly.csv (generated by cb_historical.py)
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ── Config ────────────────────────────────────────────────────────────────────
DATA_FILE     = os.path.join(os.path.dirname(os.path.abspath(__file__)), "btc_gbp_hourly.csv")
LOOKBACK_DAYS = 60

# ── Load ──────────────────────────────────────────────────────────────────────
btc = pd.read_csv(DATA_FILE)
btc["time"] = pd.to_datetime(btc["time"], utc=True)
btc.set_index("time", inplace=True)
btc.sort_index(inplace=True)

# ── Indicators ────────────────────────────────────────────────────────────────
btc["MA50"]  = btc["close"].rolling(50).mean()
btc["MA200"] = btc["close"].rolling(200).mean()

# Bollinger Bands
btc["BB_Mid"]  = btc["close"].rolling(20).mean()
btc["BB_Std"]  = btc["close"].rolling(20).std()
btc["BB_High"] = btc["BB_Mid"] + 2 * btc["BB_Std"]
btc["BB_Low"]  = btc["BB_Mid"] - 2 * btc["BB_Std"]

# RSI
delta      = btc["close"].diff()
gain       = delta.where(delta > 0, 0).rolling(14).mean()
loss_r     = (-delta.where(delta < 0, 0)).rolling(14).mean()
btc["RSI"] = 100 - (100 / (1 + gain / loss_r))

# ATR
prev_close = btc["close"].shift(1)
btc["TR"]  = pd.concat([
    btc["high"] - btc["low"],
    (btc["high"] - prev_close).abs(),
    (btc["low"]  - prev_close).abs(),
], axis=1).max(axis=1)
btc["ATR"] = btc["TR"].rolling(14).mean()

# OBV
btc["OBV"]       = (np.sign(btc["close"].diff()) * btc["volume"]).fillna(0).cumsum()
btc["vol_ma20"]  = btc["volume"].rolling(20).mean()
btc["vol_spike"] = btc["volume"] > 1.5 * btc["vol_ma20"]

btc.dropna(inplace=True)

# Subset to most recent period
recent = btc.iloc[-LOOKBACK_DAYS * 24:]  # approx hours
print(f"Loaded {len(btc):,} rows | Plotting last {LOOKBACK_DAYS} days ({len(recent):,} bars)")
print(recent[["close", "RSI", "ATR", "OBV"]].tail())

# ── Chart ─────────────────────────────────────────────────────────────────────
fig, axs = plt.subplots(5, 1, figsize=(14, 16), sharex=True)

# Price + MAs + Bollinger Bands
axs[0].plot(recent.index, recent["close"],   label="Close",   color="black", linewidth=1)
axs[0].plot(recent.index, recent["MA50"],    label="MA50",    color="blue")
axs[0].plot(recent.index, recent["MA200"],   label="MA200",   color="orange")
axs[0].plot(recent.index, recent["BB_High"], label="BB High", linestyle="--", color="green", alpha=0.7)
axs[0].plot(recent.index, recent["BB_Low"],  label="BB Low",  linestyle="--", color="red",   alpha=0.7)
axs[0].fill_between(recent.index, recent["BB_Low"], recent["BB_High"], alpha=0.05, color="blue")
axs[0].set_title("Price, MA50/200 & Bollinger Bands")
axs[0].legend(loc="upper left", fontsize=8)
axs[0].grid(True, alpha=0.3)

# RSI
axs[1].plot(recent.index, recent["RSI"], label="RSI (14)", color="purple")
axs[1].axhline(70, color="red",   linestyle="--", alpha=0.6)
axs[1].axhline(30, color="green", linestyle="--", alpha=0.6)
axs[1].fill_between(recent.index, 30, recent["RSI"], where=recent["RSI"] < 30, color="green", alpha=0.15)
axs[1].fill_between(recent.index, 70, recent["RSI"], where=recent["RSI"] > 70, color="red",   alpha=0.15)
axs[1].set_ylim(0, 100)
axs[1].set_title("RSI (14)")
axs[1].legend(loc="upper left", fontsize=8)
axs[1].grid(True, alpha=0.3)

# ATR
axs[2].plot(recent.index, recent["ATR"], label="ATR (14)", color="saddlebrown")
axs[2].set_title("ATR — Average True Range (14)")
axs[2].legend(loc="upper left", fontsize=8)
axs[2].grid(True, alpha=0.3)

# Rolling std
axs[3].plot(recent.index, recent["BB_Std"], label="Rolling Std (20)", color="darkgray")
axs[3].set_title("Rolling Standard Deviation (20)")
axs[3].legend(loc="upper left", fontsize=8)
axs[3].grid(True, alpha=0.3)

# Volume + OBV
bar_colours = ["red" if spike else "steelblue" for spike in recent["vol_spike"]]
axs[4].bar(recent.index, recent["volume"], color=bar_colours, alpha=0.5, label="Volume (red=spike)")
axs[4].plot(recent.index, recent["vol_ma20"], color="orange", label="Vol MA20")
ax4b = axs[4].twinx()
ax4b.plot(recent.index, recent["OBV"], color="green", linewidth=0.8, label="OBV", alpha=0.7)
ax4b.set_ylabel("OBV", color="green")
axs[4].set_title("Volume, Volume MA20 & OBV")
axs[4].legend(loc="upper left", fontsize=8)
axs[4].grid(True, alpha=0.3)

plt.suptitle(f"BTC-GBP Technical Dashboard — Last {LOOKBACK_DAYS} days", fontsize=13)
plt.tight_layout()
plt.show()
