"""
BTC CTA — Multi-Timeframe MA Crossover Score
=============================================
Scores 39 MA pairs simultaneously. A crossover is +1 (bullish) or -1 (bearish).
The normalised score shows consensus direction across all pairs.

Combined with RSI filter (avoid buying overbought, avoid selling oversold)
to identify higher-probability entry windows.

Data source: btc_gbp_hourly.csv (generated by cb_historical.py)
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime, timedelta

# ── Config ────────────────────────────────────────────────────────────────────
DATA_FILE     = os.path.join(os.path.dirname(os.path.abspath(__file__)), "btc_gbp_hourly.csv")
LOOKBACK_DAYS = 365           # how many days of history to plot
RSI_PERIOD    = 14
RSI_OVERSOLD  = 30
RSI_OVERBOUGHT = 70
SCORE_BUY_THRESHOLD  =  0.05  # normalised score above this → bullish consensus
SCORE_SELL_THRESHOLD = -0.05  # normalised score below this → bearish consensus

MA_PAIRS = [
    ("MA_3",   "MA_5"),   ("MA_3",   "MA_10"),  ("MA_5",   "MA_8"),
    ("MA_5",   "MA_13"),  ("MA_5",   "MA_20"),  ("MA_7",   "MA_21"),
    ("MA_7",   "MA_48"),  ("MA_9",   "MA_21"),  ("MA_10",  "MA_20"),
    ("MA_10",  "MA_50"),  ("MA_12",  "MA_26"),  ("MA_13",  "MA_34"),
    ("MA_14",  "MA_28"),  ("MA_15",  "MA_30"),  ("MA_18",  "MA_50"),
    ("MA_20",  "MA_40"),  ("MA_21",  "MA_48"),  ("MA_21",  "MA_100"),
    ("MA_25",  "MA_75"),  ("MA_30",  "MA_60"),  ("MA_30",  "MA_90"),
    ("MA_35",  "MA_100"), ("MA_40",  "MA_80"),  ("MA_40",  "MA_200"),
    ("MA_45",  "MA_90"),  ("MA_48",  "MA_96"),  ("MA_50",  "MA_100"),
    ("MA_50",  "MA_150"), ("MA_50",  "MA_200"), ("MA_55",  "MA_110"),
    ("MA_60",  "MA_120"), ("MA_70",  "MA_140"), ("MA_80",  "MA_160"),
    ("MA_90",  "MA_180"), ("MA_100", "MA_200"), ("MA_120", "MA_240"),
    ("MA_150", "MA_300"), ("MA_200", "MA_400"), ("MA_250", "MA_500"),
]

# ── Load data ─────────────────────────────────────────────────────────────────
btc = pd.read_csv(DATA_FILE)
btc["time"] = pd.to_datetime(btc["time"], utc=True)
btc.set_index("time", inplace=True)
btc.sort_index(inplace=True)

# ── Indicators ────────────────────────────────────────────────────────────────
# RSI
delta      = btc["close"].diff()
gain       = delta.where(delta > 0, 0).rolling(RSI_PERIOD).mean()
loss_r     = (-delta.where(delta < 0, 0)).rolling(RSI_PERIOD).mean()
btc["RSI"] = 100 - (100 / (1 + gain / loss_r))

# All moving averages
ma_windows = sorted({int(ma.replace("MA_", "")) for pair in MA_PAIRS for ma in pair})
for w in ma_windows:
    btc[f"MA_{w}"] = btc["close"].rolling(w).mean()

# ── MA crossover score ────────────────────────────────────────────────────────
btc["score"]        = 0.0
btc["valid_counts"] = 0

for short, long in MA_PAIRS:
    sp = btc[short].shift(1)
    lp = btc[long].shift(1)
    sc = btc[short]
    lc = btc[long]

    up   = (sp < lp) & (sc > lc)
    down = (sp > lp) & (sc < lc)
    valid = sp.notna() & lp.notna() & sc.notna() & lc.notna()

    btc["score"]        += np.where(up, 1, np.where(down, -1, 0))
    btc["valid_counts"] += valid.astype(int)

btc["norm_score"] = np.where(
    btc["valid_counts"] > 0,
    btc["score"] / btc["valid_counts"],
    0.0,
)

# ── Signals ───────────────────────────────────────────────────────────────────
cutoff  = btc.index.max() - timedelta(days=LOOKBACK_DAYS)
recent  = btc[btc.index >= cutoff].copy()

buy_signals  = recent[(recent["norm_score"] >= SCORE_BUY_THRESHOLD)  & (recent["RSI"] < RSI_OVERSOLD)]
sell_signals = recent[(recent["norm_score"] <= SCORE_SELL_THRESHOLD) & (recent["RSI"] > RSI_OVERBOUGHT)]

print(f"Data range:   {btc.index.min().date()} → {btc.index.max().date()}")
print(f"Plotting:     last {LOOKBACK_DAYS} days")
print(f"Buy signals:  {len(buy_signals)}")
print(f"Sell signals: {len(sell_signals)}")

# ── Chart ─────────────────────────────────────────────────────────────────────
fig, (ax_price, ax_score) = plt.subplots(2, 1, figsize=(14, 9), sharex=True)

ax_price.plot(recent.index, recent["close"], label="BTC Price", color="navy", linewidth=1, alpha=0.85)
ax_price.scatter(buy_signals.index,  buy_signals["close"],
                 marker="^", color="green", s=100, label="Buy (score + oversold RSI)",  zorder=5)
ax_price.scatter(sell_signals.index, sell_signals["close"],
                 marker="v", color="red",   s=100, label="Sell (score + overbought RSI)", zorder=5)
ax_price.set_title(f"BTC Price — Buy/Sell Signals (last {LOOKBACK_DAYS} days)")
ax_price.set_ylabel("Price (GBP)")
ax_price.legend(loc="upper left")
ax_price.grid(True, alpha=0.3)

ax_score.plot(recent.index, recent["norm_score"], label="Normalised Score",
              color="darkorange", linewidth=1, alpha=0.85)
ax_score.axhline( SCORE_BUY_THRESHOLD,  color="green", linestyle="--", linewidth=1, label=f"Buy threshold ({SCORE_BUY_THRESHOLD})")
ax_score.axhline( SCORE_SELL_THRESHOLD, color="red",   linestyle="--", linewidth=1, label=f"Sell threshold ({SCORE_SELL_THRESHOLD})")
ax_score.axhline(0, color="gray", linestyle="-", linewidth=0.6)
ax_score.fill_between(recent.index, 0, recent["norm_score"],
                      where=recent["norm_score"] > 0, color="green", alpha=0.1)
ax_score.fill_between(recent.index, 0, recent["norm_score"],
                      where=recent["norm_score"] < 0, color="red",   alpha=0.1)
ax_score.set_title("MA Crossover Consensus Score (39 pairs, normalised)")
ax_score.set_ylabel("Score")
ax_score.set_xlabel("Date")
ax_score.legend(loc="upper left")
ax_score.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()
